version: '3.9'

x-default: &node
  image: bitnami/spark:3.5.1
  volumes:
    - ./drivers:/jdbc
    - ./scripts:/tmp/scripts
    - ./tables:/tmp/tables
    - ./target:/tmp/target:rw
  secrets:
    - IPTS_PASSWORD
  networks:
    - sparknet

services:
  spark-node-master:
    <<: *node
    container_name: spark-node-master
    hostname: spark-node-master
    environment:
      - SPARK_MODE=master
      - SPARK_PUBLIC_DNS=10.129.122.29
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - IPTS_HOSTNAME
      - IPTS_PORT
      - IPTS_SERVICE_NAME
      - IPTS_USERNAME
      - IPTS_TABLE
    ports:
      - 4040:4040
      - 8080:8080
      - 7077:7077

  spark-node-worker:
    <<: *node
    container_name: spark-node-worker
    hostname: spark-node-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_PUBLIC_DNS=10.129.122.29
      - SPARK_MASTER_URL=spark://spark-node-master:7077
      - SPARK_WORKER_MEMORY=96G
      - SPARK_WORKER_CORES=32
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - IPTS_HOSTNAME
      - IPTS_PORT
      - IPTS_SERVICE_NAME
      - IPTS_USERNAME
      - IPTS_TABLE
    ports:
      - 8081:8081

networks:
  sparknet:
    ipam:
      config:
        - subnet: 211.55.0.0/16
    name: sparknet

secrets:
  IPTS_PASSWORD:
    file: secrets/IPTS_PASSWORD
