define:
  min_year: &min_year 2022

# Jobs that run daily at 1AM, typically getting the 2 most
# recent years of data for critical tables
default_jobs:
  ADDN:
    table_name: iasworld.ADDN
    min_year: *min_year
  APRVAL:
    table_name: iasworld.APRVAL
    min_year: *min_year
  ASMT_ALL:
    table_name: iasworld.ASMT_ALL
    min_year: *min_year
  ASMT_HIST:
    table_name: iasworld.ASMT_HIST
    min_year: *min_year
  COMDAT:
    table_name: iasworld.COMDAT
    min_year: *min_year
  CVLEG:
    table_name: iasworld.CVLEG
    min_year: *min_year
    cur: null
  DWELDAT:
    table_name: iasworld.DWELDAT
    min_year: *min_year
  ENTER:
    table_name: iasworld.ENTER
    min_year: null
    max_year: null
    cur: null
    predicates_path: null
  HTPAR:
    table_name: iasworld.HTPAR
    min_year: *min_year
  LAND:
    table_name: iasworld.LAND
    min_year: *min_year
  LEGDAT:
    table_name: iasworld.LEGDAT
    min_year: *min_year
  OBY:
    table_name: iasworld.OBY
    min_year: *min_year
  OWNDAT:
    table_name: iasworld.OWNDAT
    min_year: *min_year
  PARDAT:
    table_name: iasworld.PARDAT
    min_year: *min_year
  PERMIT:
    table_name: iasworld.PERMIT
    min_year: null
    max_year: null
    cur: null
    predicates_path: null
  SALES:
    table_name: iasworld.SALES
    min_year: null
    max_year: null
  SPLCOM:
    table_name: iasworld.SPLCOM
    min_year: *min_year
    cur: null
    predicates_path: null

# Jobs that run on the weekend, fully refreshing all critical tables
weekend_jobs:
  AASYSJUR:
    table_name: iasworld.AASYSJUR
    min_year: null
    max_year: null
    cur: null
    predicates_path: null
  ADDN:
    table_name: iasworld.ADDN
  ADDRINDX:
    table_name: iasworld.ADDRINDX
  APRVAL:
    table_name: iasworld.APRVAL
  ASMT_ALL:
    table_name: iasworld.ASMT_ALL
  ASMT_HIST:
    table_name: iasworld.ASMT_HIST
  CNAME:
    table_name: iasworld.CNAME
    min_year: null
    max_year: null
    predicates_path: null
  COMDAT:
    table_name: iasworld.COMDAT
  COMNT:
    table_name: iasworld.COMNT
    min_year: null
    max_year: null
    cur: null
    predicates_path: null
  CVLEG:
    table_name: iasworld.CVLEG
    cur: null
  CVOWN:
    table_name: iasworld.CVOWN
    cur: null
    predicates_path: null
  CVTRAN:
    table_name: iasworld.CVTRAN
    cur: null
    predicates_path: null
  DEDIT:
    table_name: iasworld.DEDIT
    min_year: null
    max_year: null
    cur: null
    predicates_path: null
  DWELDAT:
    table_name: iasworld.DWELDAT
  ENTER:
    table_name: iasworld.ENTER
    min_year: null
    max_year: null
    cur: null
    predicates_path: null
  EXADMN:
    table_name: iasworld.EXADMN
  EXAPP:
    table_name: iasworld.EXAPP
  EXCODE:
    table_name: iasworld.EXCODE
    predicates_path: null
  EXDET:
    table_name: iasworld.EXDET
  HTAGNT:
    table_name: iasworld.HTAGNT
    min_year: null
    max_year: null
    cur: null
    predicates_path: null
  HTDATES:
    table_name: iasworld.HTDATES
    cur: null
  HTPAR:
    table_name: iasworld.HTPAR
  LAND:
    table_name: iasworld.LAND
  LEGDAT:
    table_name: iasworld.LEGDAT
  LPMOD:
    table_name: iasworld.LPMOD
    min_year: null
    max_year: null
    cur: null
    predicates_path: null
  LPNBHD:
    table_name: iasworld.LPNBHD
    min_year: null
    max_year: null
    cur: null
    predicates_path: null
  OBY:
    table_name: iasworld.OBY
  OWNDAT:
    table_name: iasworld.OWNDAT
  PARDAT:
    table_name: iasworld.PARDAT
  PERMIT:
    table_name: iasworld.PERMIT
    min_year: null
    max_year: null
    cur: null
    predicates_path: null
  RCOBY:
    table_name: iasworld.RCOBY
    min_year: null
    max_year: null
    cur: null
    predicates_path: null
  SALES:
    table_name: iasworld.SALES
    min_year: null
    max_year: null
  SPLCOM:
    table_name: iasworld.SPLCOM
    cur: null
    predicates_path: null
  VALCLASS:
    table_name: iasworld.VALCLASS
    cur: null
    predicates_path: null

# Jobs with a good mix of situations used for testing
test_jobs:
  AASYSJUR:
    table_name: iasworld.AASYSJUR
    min_year: null
    max_year: null
    cur: null
    predicates_path: null
  ADDN:
    table_name: iasworld.ADDN
    min_year: *min_year
  ADDRINDX:
    table_name: iasworld.ADDRINDX
    min_year: 2011
    max_year: 2013
  APRVAL:
    table_name: iasworld.APRVAL
    max_year: 2004
    cur: ["Y"]
  SALES:
    table_name: iasworld.SALES
    min_year: null
    max_year: null
  VALCLASS:
    table_name: iasworld.VALCLASS
    cur: null
    predicates_path: null
