# Default arguments used for the CLI. Can be overridden using the corresponding
# flag at runtime
default_args:
  extract_target: "prod"
  run_github_workflow: False
  run_glue_crawler: False
  upload_logs: False
  upload_data: False

# Data type overrides are necessary to maintain parity/consistency with sqoop.
# Schema overrides are defined in three places, with each overriding the last:
#   1. By default, NUMBER Oracle types are converted to DECIMAL(10,0)
#      and TIMESTAMP Oracle types are converted to STRING
#   2. Global schema overrides, as defined below
#   3. Table schema overrides, defined in table_definitions.yaml
#
# NOTE: taxyr MUST be an integer in order for Spark to properly pushdown
# filters (and thus make queries go fast)
global_schema_overrides:
  deactivat: STRING
  taxyr: INTEGER
