define: &min_year 2022

# Jobs that run daily at 1AM, typically getting the 2 most
# recent years of data for critical tables
default_jobs:
  addn:
    table_name: iasworld.addn
    min_year: *min_year
  aprval:
    table_name: iasworld.aprval
    min_year: *min_year
  asmt_all:
    table_name: iasworld.asmt_all
    min_year: *min_year
  asmt_hist:
    table_name: iasworld.asmt_hist
    min_year: *min_year
  comdat:
    table_name: iasworld.comdat
    min_year: *min_year
  cvleg:
    table_name: iasworld.cvleg
    min_year: *min_year
  dweldat:
    table_name: iasworld.dweldat
    min_year: *min_year
  enter:
    table_name: iasworld.enter
    predicates_path: null
    min_year: null
    max_year: null
    cur: null
  htpar:
    table_name: iasworld.htpar
    min_year: *min_year
  land:
    table_name: iasworld.land
    min_year: *min_year
  legdat:
    table_name: iasworld.legdat
    min_year: *min_year
  oby:
    table_name: iasworld.oby
    min_year: *min_year
  owndat:
    table_name: iasworld.owndat
    min_year: *min_year
  pardat:
    table_name: iasworld.pardat
    min_year: *min_year
  permit:
    table_name: iasworld.permit
    predicates_path: null
    min_year: null
    max_year: null
    cur: null
  sales:
    table_name: iasworld.sales
    min_year: null
    max_year: null
  splcom:
    table_name: iasworld.splcom
    min_year: *min_year

# Jobs that run on the weekend, fully refreshing all critical tables
weekend_jobs:
  aasysjur:
    table_name: iasworld.aasysjur
    predicates_path: null
    min_year: null
    max_year: null
    cur: null
  addn:
    table_name: iasworld.addn
  addrindx:
    table_name: iasworld.addrindx
  aprval:
    table_name: iasworld.aprval
  asmt_all:
    table_name: iasworld.asmt_all
  asmt_hist:
    table_name: iasworld.asmt_hist
  cname:
    table_name: iasworld.cname
    predicates_path: null
    min_year: null
    max_year: null
    cur: null
  comdat:
    table_name: iasworld.comdat
  comnt:
    table_name: iasworld.comnt
    predicates_path: null
    min_year: null
    max_year: null
    cur: null
  cvleg:
    table_name: iasworld.cvleg
  cvown:
    table_name: iasworld.cvown
  cvtran:
    table_name: iasworld.cvtran
  dedit:
    table_name: iasworld.dedit
    predicates_path: null
    min_year: null
    max_year: null
    cur: null
  dweldat:
    table_name: iasworld.dweldat
  enter:
    table_name: iasworld.enter
    predicates_path: null
    min_year: null
    max_year: null
    cur: null
  exadmn:
    table_name: iasworld.exadmn
  exapp:
    table_name: iasworld.exapp
  excode:
    table_name: iasworld.excode
  exdet:
    table_name: iasworld.exdet
  htagnt:
    table_name: iasworld.htagnt
    predicates_path: null
    min_year: null
    max_year: null
    cur: null
  htdates:
    table_name: iasworld.htdates
  htpar:
    table_name: iasworld.htpar
  land:
    table_name: iasworld.land
  legdat:
    table_name: iasworld.legdat
  lpmod:
    table_name: iasworld.lpmod
    predicates_path: null
    min_year: null
    max_year: null
    cur: null
  lpnbhd:
    table_name: iasworld.lpnbhd
    predicates_path: null
    min_year: null
    max_year: null
    cur: null
  oby:
    table_name: iasworld.oby
  owndat:
    table_name: iasworld.owndat
  pardat:
    table_name: iasworld.pardat
  permit:
    table_name: iasworld.permit
    predicates_path: null
    min_year: null
    max_year: null
    cur: null
  rcoby:
    table_name: iasworld.rcoby
    predicates_path: null
    min_year: null
    max_year: null
    cur: null
  sales:
    table_name: iasworld.sales
    min_year: null
    max_year: null
    cur: null
  splcom:
    table_name: iasworld.splcom
  valclass:
    table_name: iasworld.valclass
    predicates_path: null
    min_year: null
    max_year: null
    cur: null

# Jobs with a good mix of situations used for testing
test_jobs:
  aasysjur:
    table_name: iasworld.aasysjur
    predicates_path: null
    min_year: null
    max_year: null
    cur: null
  addn:
    table_name: iasworld.addn
    min_year: *min_year
  addrindx:
    table_name: iasworld.addrindx
    min_year: 2011
    max_year: 2013
  aprval:
    table_name: iasworld.aprval
    max_year: 2004
    cur: ["Y"]
  sales:
    table_name: iasworld.sales
    min_year: null
    max_year: null
  valclass:
    table_name: iasworld.valclass
    predicates_path: null
    min_year: null
    max_year: null
    cur: null
