define:
  global_min_year: &global_min_year 1999

# Table definitions containing the possible values to use for each table job,
# as well as table-level schema overrides per column. Null values indicate
# the column is not applicable to the table, or that there should be no
# check on the possible value
tables:
  aasysjur:
    min_year: null
    has_cur: false
    has_parid: false
  addn:
    min_year: *global_min_year
    has_cur: true
    has_parid: true
  addrindx:
    min_year: *global_min_year
    has_cur: true
    has_parid: true
    schema_overrides:
      xcoord: DECIMAL(15,8)
      ycoord: DECIMAL(15,8)
  aprval:
    min_year: *global_min_year
    has_cur: true
    has_parid: true
  asmt_all:
    min_year: *global_min_year
    has_cur: true
    has_parid: true
  asmt_hist:
    min_year: *global_min_year
    has_cur: true
    has_parid: true
  cname:
    min_year: null
    has_cur: true
    has_parid: false
  comdat:
    min_year: *global_min_year
    has_cur: true
    has_parid: true
  comnt:
    min_year: null
    has_cur: false
    has_parid: false
  cvleg:
    min_year: 1900
    has_cur: false
    has_parid: true
    schema_overrides:
      xcoord: DECIMAL(15,8)
      ycoord: DECIMAL(15,8)
      zcoord: DECIMAL(15,8)
  cvown:
    min_year: 2001
    has_cur: false
    has_parid: false
  cvtran:
    min_year: 1900
    has_cur: false
    has_parid: false
  dedit:
    min_year: null
    has_cur: false
    has_parid: false
  dweldat:
    min_year: *global_min_year
    has_cur: true
    has_parid: true
  enter:
    min_year: null
    has_cur: false
    has_parid: false
  exadmn:
    min_year: 1998
    has_cur: true
    has_parid: true
  exapp:
    min_year: *global_min_year
    has_cur: true
    has_parid: true
  excode:
    min_year: 1993
    has_cur: true
    has_parid: false
  exdet:
    min_year: 1998
    has_cur: true
    has_parid: true
  htagnt:
    min_year: null
    has_cur: false
    has_parid: false
  htdates:
    min_year: 2021
    has_cur: false
    has_parid: true
  htpar:
    min_year: *global_min_year
    has_cur: true
    has_parid: true
  land:
    min_year: *global_min_year
    has_cur: true
    has_parid: true
    # Override land rates that are stored as NUMBER types with no set precision
    # or scale, meaning they default to the maximum precision and scale that
    # Oracle supports (38 and 127, respectively). Presto performance is best up
    # to a precision of 18, so we set precision to that high bar and truncate
    # scale to a high but reasonable value.
    schema_overrides:
      bdecr: DECIMAL(18,10)
      bincr: DECIMAL(18,10)
      brate: DECIMAL(18,10)
      bsize: DECIMAL(18,10)
      odecr: DECIMAL(18,10)
      oincr: DECIMAL(18,10)
      orate: DECIMAL(18,10)
      osize: DECIMAL(18,10)
  legdat:
    min_year: *global_min_year
    has_cur: true
    has_parid: true
    schema_overrides:
      xcoord: DECIMAL(15,8)
      ycoord: DECIMAL(15,8)
      zcoord: DECIMAL(15,8)
  lpmod:
    min_year: null
    has_cur: false
    has_parid: false
  lpnbhd:
    min_year: null
    has_cur: false
    has_parid: false
  oby:
    min_year: *global_min_year
    has_cur: true
    has_parid: true
  owndat:
    min_year: *global_min_year
    has_cur: true
    has_parid: true
  pardat:
    min_year: *global_min_year
    has_cur: true
    has_parid: true
  permit:
    min_year: null
    has_cur: false
    has_parid: false
  rcoby:
    min_year: null
    has_cur: false
    has_parid: false
  sales:
    min_year: null
    has_cur: true
    has_parid: true
  splcom:
    min_year: 2021
    has_cur: false
    has_parid: false
  valclass:
    min_year: 2015
    has_cur: false
    has_parid: false
